name: Deploy Account Service

on:
  push:
    paths:
      - 'services/account/**'
    branches: [main]

jobs:
  deploy:
    name: Build and Deploy to GCP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: digitnxt
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/digitnxt/digit-docker-repo/account:latest ./services/account
          docker push us-central1-docker.pkg.dev/digitnxt/digit-docker-repo/account:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy account \
            --image us-central1-docker.pkg.dev/digitnxt/digit-docker-repo/account:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 8080