version: "3.8"
services:
  minio:
    image: minio/minio:latest
    ports:
      - "9002:9000"
      - "9003:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  filestore:
    build: .
    network_mode: host
    environment:
      DB_HOST: localhost
      DB_PORT: 5433
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      MINIO_ENDPOINT: localhost:9002
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: filestore
      MINIO_READ_BUCKET: filestore
      MINIO_USE_SSL: "false"
    volumes:
      - ./.env:/app/.env
  
    depends_on:
      - minio

volumes:
  minio_data:
