server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Tail Docker's JSON log files directly
  - job_name: docker-files
    pipeline_stages:
      - docker: {}        # parse docker JSON log format
    static_configs:
      - targets: [localhost]
        labels:
          job: docker-logs
          __path__: /var/lib/docker/containers/*/*-json.log

  # Also auto-discover containers via docker.sock to add rich labels
  - job_name: docker-discovery
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: container
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: service
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: project
      - source_labels: ['__meta_docker_container_label_env']
        target_label: env
      - source_labels: ['__meta_docker_container_label_app']
        target_label: app 