global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'loki'
    metrics_path: /metrics
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'promtail'
    metrics_path: /metrics
    static_configs:
      - targets: ['promtail:9080']

  # Optional host metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] 