apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: dynamic-jwt
  namespace: egov
plugin: dynamic-jwt
config:
  issuer: "http://keycloak.keycloak.svc.cluster.local:8080/keycloak-test/realms/DEMOUSERCAMUNDA"
  jwt_valid_time: 7200
  verify_signature: true
  key_claim_name: "iss"
  algorithm: "RS256"
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: keycloak-rbac
  namespace: egov
plugin: keycloak-rbac
config:
  keycloak_url: "http://keycloak.keycloak.svc.cluster.local:8080/keycloak-test"
  realm: "DEMOUSERCAMUNDA"
  client_id: "admin-cli"
  well_known: "/realms/DEMOUSERCAMUNDA/.well-known/openid_configuration"
  introspection_endpoint: "/realms/DEMOUSERCAMUNDA/protocol/openid-connect/token/introspect"
  timeout: 60000
  keepalive: 60000 